#!/bin/sh

set -e

sudo DEBIAN_FRONTEND=noninteractive apt-get install -qy \
  ruby chef ruby-commander ruby-text-table rake ruby-rspec curl

if [ -d /vagrant ]; then
  for env in "$@"; do
    if ! grep -q "$env" ~/.bashrc; then
      echo "export $env" >> ~/.bashrc
    fi
  done
  if ! grep -q /vagrant/.env ~/.bashrc; then
    echo 'PWD=/vagrant . /vagrant/.env' >> ~/.bashrc
  fi
  if [ ! -f ~/.bash_profile ]; then
    echo ". ~/.bashrc" > ~/.bash_profile
  fi
  cd /vagrant
fi

sudo systemctl stop chef-client
sudo systemctl disable chef-client
