#!/bin/sh

set -e

exit # debdry broken; no patience to debug that now

export DEBIAN_FRONTEND=noninteractive
export DEBFULLNAME='Antonio Terceiro'
export DEBEMAIL=terceiro@debian.org

# FIXME debdry should already depend on python3-apt
sudo apt-get install -qy dctrl-tools debdry gem2deb python3-apt

base=$(dirname $0)/..
cd $base
debdry
grep-dctrl -n -s Depends,Build-Depends . debian/control | sed -e 's/,\s*/\n/g; s/|\s*\S*//; s/${[^}]*}//g; s/([^)]*)//g' | xargs sudo apt-get install -qy
debdry --restore
