#!/bin/sh

set -e

export DEBIAN_FRONTEND=noninteractive

sudo apt-get install -qy dctrl-tools debdry gem2deb apt-file

if [ -d /vagrant ]; then
  for env in "$@"; do
    if ! grep -q "$env" ~/.bashrc; then
      echo "export $env" >> ~/.bashrc
    fi
  done
  if [ ! -f ~/.bash_profile ]; then
    echo ". ~/.bashrc" > ~/.bash_profile
  fi
  cd /vagrant
fi

apt-file update
./utils/debdry
grep-dctrl -n -s Depends,Build-Depends . debian/control | sed -e 's/,\s*/\n/g; s/|\s*\S*//; s/${[^}]*}//g; s/([^)]*)//g' | xargs sudo apt-get install -qy
rm -rf debian
