#!/bin/sh

set -e

sudo -v
sudo redir --lport 80  --cport 8080 &
sudo redir --lport 443 --cport 8443 &

cleanup() {
  sudo -v
  sudo pkill -9 redir
}

echo "Forwarding ports 80 and 443"
echo "Hit ctrl-c to stop"
echo
trap cleanup INT TERM EXIT
tail -f /dev/null
echo
